version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: monthly
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: sidekiq
    versions:
    - 5.2.4
  - dependency-name: rubocop
    versions:
    - 1.7.0
    - 1.9.0
  - dependency-name: simplecov-console
    versions:
    - 0.8.0
    - 0.9.0
  - dependency-name: rails
    versions:
    - 6.1.0
    - 6.1.1
  - dependency-name: nokogiri
    versions:
    - 1.11.0
  - dependency-name: simplecov
    versions:
    - 0.20.0
  - dependency-name: jbuilder
    versions:
    - 2.10.1
  - dependency-name: shoulda-matchers
    versions:
    - 4.4.1
