inherit_from: .rubocop_todo.yml
Documentation:
  Enabled: false
Metrics/LineLength:
  Max: 120
Metrics/MethodLength:
  CountComments: false
  Max: 20
Metrics/ClassLength:
  CountComments: false
  Max: 100
Lint/HandleExceptions:
  Enabled: false
Style/SymbolArray:
  EnforcedStyle: percent
Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    default: ()
    '%i': ()
    '%w': ()
Metrics/AbcSize:
  Enabled: false

AllCops:
  Include:
    - Rakefile
    - config.ru

  Exclude:
    - Gemfile
    - db/schema.rb
    - spec/spec_helper.rb
    - spec/rails_helper.rb
    - bin/*
    - config/initializers/devise.rb
    - lib/tasks/fill_data.rake
    - config/environments/development.rb
