env:
  global:
    - CC_TEST_REPORTER_ID=e5846986ece18945bd1d9bd02380b419a7d82ca0e9a8584f5fb03cebcc4dccf3
language: ruby
dist: trusty
rvm:
  - 2.5.1
notifications:
  - false
bundler_args: --jobs=2
script:
  - sudo apt-get update
  - sudo apt-get install chromium-chromedriver
  - bundle exec rake db:setup
  - bundle exec rspec spec
before_script:
  - 'export PATH=$PATH:/usr/lib/chromium-browser/'
  - cp config/database.example.yml config/database.yml
  - psql -c 'create database bbtt_test;' -U postgres
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

cache: bundler
services:
  - postgresql
addons:
  postgresql: "9.6"
  chrome: stable
  apt:
    packages:
      - chromium-chromedriver
