language: ruby
rvm:
  - 2.5.0
env:
  - DB=postgres
bundler_args: --jobs=2
script:
  - bundle exec rake db:setup
  - bundle exec rake spec
before_script:
  - cp config/database.example.yml config/database.yml
  - psql -c 'create database bbtt_test;' -U postgres

cache: bundler
services:
  - postgresql
addons:
  postgresql: "9.6"
  chrome: stable
  apt:
    packages:
      - chromium-chromedriver
